'use client';
import {useEffect,useState} from 'react';
import {registerWorkspaceTool} from '@/lib/webmcp';
import {Activity,ArrowUpRight,Download,RefreshCw,Plus,Store,Video,ShieldCheck,Clock3,Database} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {initialProfiles,fields,contribution,yesterday,inspectData,type Profile,type Daily,type Report} from '@/lib/model';
const num=(v:unknown)=>typeof v==='number'?v.toLocaleString('en-US',{maximumFractionDigits:2}):'—';
const money=(v:unknown)=>typeof v==='number'?'$'+v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
export default function Home(){
 const [profiles,setProfiles]=useState<Profile[]>(initialProfiles),[records,setRecords]=useState<Daily[]>([]),[reports,setReports]=useState<Report[]>([]);
 const [date,setDate]=useState(yesterday),[filter,setFilter]=useState('all'),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const [edit,setEdit]=useState(false),[chosen,setChosen]=useState('pop-1'),[form,setForm]=useState<Record<string,string>>({}),[importOpen,setImportOpen]=useState(false),[csv,setCsv]=useState('');
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/workspace');if(!r.ok)throw Error('工作台数据暂时无法读取，请稍后刷新。');const d=await r.json() as {profiles:Profile[];records:Daily[];reports:Report[]};setProfiles(d.profiles);setRecords(d.records);setReports(d.reports);setLoaded(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void Promise.resolve().then(()=>load());},[]);
 useEffect(()=>registerWorkspaceTool(),[]);
 async function save(payload:unknown){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string;message?:string};if(!r.ok)throw Error(d.error||'保存失败');await load();setNotice(d.message||'已保存');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const rows=profiles.filter(p=>p.kind==='店铺'&&(filter==='all'||p.id===filter)).map(p=>({p,r:records.find(r=>r.profile===p.id&&r.date===date)}));
 const coverage=rows.filter(x=>x.r).length;
 const sum=(k:string)=>rows.length&&rows.every(x=>typeof x.r?.[k]==='number')?rows.reduce((a,x)=>a+Number(x.r![k]),0):null;
 const profits=rows.map(x=>contribution(x.r));const totalProfit=profits.length&&profits.every(x=>x!==null)?profits.reduce<number>((a,x)=>a+(x||0),0):null;
 const alerts=inspectData(records,profiles,date);
 function openEntry(id='pop-1'){setChosen(id);const r=records.find(r=>r.profile===id&&r.date===date);setForm(Object.fromEntries([['source',String(r?.source||'后台人工记录')],...fields.map(([k])=>[k,r?.[k]==null?'':String(r[k])])]));setEdit(true);}
 function download(){const blob=new Blob(['\uFEFF'+['date,profile,source,'+fields.map(f=>f[0]).join(','),date+',pop-1,后台导出,'+fields.map(()=> '').join(',')].join('\r\n')],{type:'text/csv;charset=utf-8'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='TK每日数据模板.csv';a.click();URL.revokeObjectURL(u);}
 return <div className="workspace"><header className="topbar"><div className="brand"><span className="brandmark">TK</span><span>POD OPERATIONS</span><span className="branddivider"/><span>手机壳工作台</span></div><span className="private"><ShieldCheck size={16}/>个人工作空间</span></header>
 <main><div className="pageheading"><div><p className="eyebrow">美国市场 · 3 店 / 4 账号</p><h1>每日运营，一处掌握<span className="accentdot">.</span></h1></div><div className="actions"><Button variant="outline" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>刷新</Button><Button onClick={()=>openEntry()} disabled={!loaded||busy}><Plus size={16}/>录入数据</Button></div></div>
 <div className="connection"><Database size={26}/><div><strong>等待 API 接入</strong><p>紫鸟位于另一台电脑。当前可录入和导入日报，尚未开启店铺自动采集。</p></div><button onClick={()=>setTab('sources')}>数据接入 <ArrowUpRight size={17}/></button></div>
 {error&&<div className="feedback error" role="alert">{error}</div>}{notice&&<output className="feedback">{notice}</output>}
 <div className="filterbar"><div className="actions"><label className="datefield" htmlFor="report-date">统计日期 <Input id="report-date" aria-label="统计日期" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><Select value={filter} onValueChange={v=>v&&setFilter(v)}><SelectTrigger><SelectValue>{filter==='all'?'全部店铺':profiles.find(p=>p.id===filter)?.name}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">全部店铺</SelectItem>{profiles.filter(p=>p.kind==='店铺').map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><span>美西时间 · USD · 数据覆盖 {coverage}/{rows.length} 店</span></div>
 <section className="metrics">{[{title:'支付销售额',value:money(sum('gmv')),note:'店铺数据齐全后汇总',Icon:Store},{title:'支付订单',value:num(sum('orders')),note:'各店支付订单数合计',Icon:Activity},{title:'贡献利润',value:money(totalProfit),note:'退款与变动成本齐全后计算',Icon:ShieldCheck},{title:'超时未揽收',value:num(sum('late')),note:'优先处理的履约订单',Icon:Clock3}].map(({title,value,note,Icon})=><article className="metric" key={title}><div>{title}<Icon size={18}/></div><strong>{value}</strong><p>{note}</p></article>)}</section>
 <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="worktabs"><TabsTrigger value="overview">店铺总览</TabsTrigger><TabsTrigger value="content">内容账号</TabsTrigger><TabsTrigger value="reports">每日巡检</TabsTrigger><TabsTrigger value="sources">数据接入</TabsTrigger></TabsList>
 <TabsContent value="overview"><div className="twocol"><section className="panel"><div className="panelheading"><h2>店铺表现</h2><span>{date}</span></div><Table><TableHeader><TableRow>{['店铺','销售额','订单','贡献利润','数据状态',''].map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(({p,r})=><TableRow key={p.id}><TableCell><strong>{p.name}</strong><small>{p.type} · 美国</small></TableCell><TableCell>{money(r?.gmv)}</TableCell><TableCell>{num(r?.orders)}</TableCell><TableCell>{money(contribution(r))}</TableCell><TableCell><span className={r?'pill good':'pill'}>{r?'已记录':'无数据'}</span></TableCell><TableCell><button className="textbutton" disabled={!loaded} onClick={()=>openEntry(p.id)}>录入</button></TableCell></TableRow>)}</TableBody></Table><p className="footnote">贡献利润 = 销售额 − 退款 − 商品成本 − 运费 − 平台费 − 佣金 − 广告 − 其他变动费用。不是净利润；缺失值不当作零。</p></section><section className="panel focus"><div className="panelheading"><h2>优先关注</h2><span className="pill">{alerts.length} 项</span></div>{alerts.slice(0,4).map((a,i)=><div className="step" key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{a}</p></div>)}{alerts.length>4&&<button className="textbutton" onClick={()=>setTab('reports')}>查看巡检详情 →</button>}</section></div></TabsContent>
 <TabsContent value="content"><section className="panel"><div className="panelheading"><h2>内容账号表现</h2><span>与店铺销售分开统计，避免重复归因</span></div><Table><TableHeader><TableRow>{['账号','视频发布','播放','商品点击','点击率',''].map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{profiles.filter(p=>p.kind==='账号').map(p=>{const r=records.find(r=>r.profile===p.id&&r.date===date);return <TableRow key={p.id}><TableCell><Video size={16} className="inlineicon"/>{p.name}</TableCell><TableCell>{num(r?.videos)}</TableCell><TableCell>{num(r?.views)}</TableCell><TableCell>{num(r?.clicks)}</TableCell><TableCell>{typeof r?.views==='number'&&r.views>0&&typeof r.clicks==='number'?(r.clicks/r.views*100).toFixed(2)+'%':'—'}</TableCell><TableCell><button className="textbutton" disabled={!loaded} onClick={()=>openEntry(p.id)}>录入</button></TableCell></TableRow>})}</TableBody></Table></section></TabsContent>
 <TabsContent value="reports"><section className="panel"><div className="panelheading"><div><h2>每日巡检记录</h2><p className="muted">计划每日 09:00 美西时间检查昨日数据。自动采集等待 API。</p></div><Button disabled={!loaded||busy} onClick={()=>void save({action:'inspect',date})}><Activity size={16}/>检查所选日期</Button></div>{reports.length?reports.map((r,i)=><article className="report" key={i}><strong>{r.date}</strong><small>检查时间 {new Date(r.at).toLocaleString('zh-CN',{timeZone:'America/Los_Angeles'})} PT</small>{r.alerts.map((a,j)=><p key={j}>{a}</p>)}</article>):<div className="empty"><Clock3 size={30}/><h3>还没有巡检记录</h3><p>检查所选日期，生成缺数、亏损与履约提醒。</p></div>}</section></TabsContent>
 <TabsContent value="sources"><div className="twocol"><section className="panel"><div className="panelheading"><h2>店铺与账号登记</h2><Button disabled={!loaded||busy} onClick={()=>void save({action:'profiles',profiles})}>保存登记</Button></div><p className="footnote">只登记紫鸟环境名称，不保存密码或登录凭据。</p>{profiles.map((p,i)=><div className="profileedit" key={p.id}><span>{p.type}<small>{p.id}</small></span><Input aria-label={p.id+'名称'} value={p.name} onChange={e=>setProfiles(profiles.map((x,j)=>i===j?{...x,name:e.target.value}:x))}/><Input aria-label={p.id+'紫鸟环境'} placeholder="紫鸟环境名称 / 设备备注" value={p.environment} onChange={e=>setProfiles(profiles.map((x,j)=>i===j?{...x,environment:e.target.value}:x))}/></div>)}</section><section className="panel"><div className="panelheading"><h2>数据入口</h2></div><h3>日报导入</h3><p className="muted">使用工作台 CSV 模板。同一日期和账号更新记录，不重复累加。平台原始报表需先映射字段。</p><div className="actions spaced"><Button variant="outline" onClick={download}><Download size={16}/>下载模板</Button><Button disabled={!loaded} onClick={()=>setImportOpen(true)}>导入 CSV</Button></div><hr/><h3>API 接入待配置</h3><p className="muted">收到接口文档后连接只读数据源。当前尚未进行店铺授权，也未进行自动采集。</p><hr/><h3>已确认的履约条件</h3><p>GOFO $3.35 / USPS $4.05</p><p className="muted">美国本土 48 州＋华盛顿特区。生产通常 1–2 天；与首次物流揽收分开检查。</p></section></div></TabsContent>
 </Tabs><footer>TK POD · 统计口径：美西时间 / 美元<span>{loaded?'工作台数据已读取':'正在连接工作台'}</span></footer></main>
 <Dialog open={edit} onOpenChange={setEdit}><DialogContent className="entrydialog"><DialogTitle>{profiles.find(p=>p.id===chosen)?.name} · {date}</DialogTitle><DialogDescription>空白表示未知；确认没有发生的项目填 0。保存会更新这一天的记录。</DialogDescription><form onSubmit={async e=>{e.preventDefault();const row={date,profile:chosen,source:form.source,...Object.fromEntries(fields.map(([k])=>[k,form[k]===''||form[k]==null?null:Number(form[k])]))};if(await save({action:'records',records:[row]}))setEdit(false);}}><label htmlFor="data-source">数据来源<Input id="data-source" required value={form.source||''} onChange={e=>setForm({...form,source:e.target.value})}/></label><div className="formgrid">{fields.filter(([k])=>chosen.startsWith('account')?['views','clicks','videos'].includes(k):!['views','clicks','videos'].includes(k)).map(([k,label])=><label key={k} htmlFor={k}>{label}<Input id={k} type="number" min="0" step={['orders','pending','late','violations','views','clicks','videos'].includes(k)?'1':'0.01'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder="未知"/></label>)}</div><Button type="submit" disabled={busy}>保存日报</Button></form></DialogContent></Dialog>
 <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="entrydialog"><DialogTitle>导入日报 CSV</DialogTitle><DialogDescription>最多 500 行，USD。空白保留为未知。同一天同一账号覆盖更新。导入失败时不会部分写入。</DialogDescription><input type="file" accept=".csv,text/csv" aria-label="选择日报 CSV" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>1000000){setError('文件请小于 1 MB');return;}setCsv(await f.text());}}}/><textarea aria-label="CSV 内容" rows={8} value={csv} onChange={e=>setCsv(e.target.value)} placeholder="date,profile,source,gmv,orders,..."/><Button disabled={busy||!csv.trim()} onClick={async()=>{if(await save({action:'csv',csv}))setImportOpen(false);}}>验证并导入</Button></DialogContent></Dialog>
 </div>;
}