'use client';
import {groupInsights,type InsightRow} from '@/lib/intelligence';
import type {Daily} from '@/lib/model';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
const number=(v:unknown)=>typeof v==='number'?v.toLocaleString('en-US',{maximumFractionDigits:2}):'—';
const money=(v:unknown)=>typeof v==='number'?'$'+v.toFixed(2):'—';
export function IntelligencePanels({rows,records,start,end,profile}:{rows:InsightRow[];records:(Daily|undefined)[];start:string;end:string;profile:string}){
 const hourly=groupInsights(rows,'hourly',start,end,profile);const sum=(key:string)=>records.length&&records.every(r=>typeof r?.[key]==='number')?records.reduce((n,r)=>n+Number(r![key]),0):null;
 return <div className="intelligence-stack"><section className="panel"><div className="panelheading"><h2>支付、优惠与结算</h2><span>按所选区间统计</span></div><div className="detail-grid">{[['payAmount','买家支付'],['escrowAmount','托管金额'],['discountAmount','优惠金额'],['productSales','商品销售'],['productRefundAmount','商品退款'],['commission','达人佣金'],['shipping','已记录运费'],['settledOrders','已结算订单'],['refunding','退款中订单']].map(([k,label])=><div key={k}><span>{label}</span><strong>{['settledOrders','refunding'].includes(k)?number(sum(k)):money(sum(k))}</strong></div>)}</div><p className="footnote">各金额口径独立，不能直接相加作为销售额或利润；缺失字段保持未知。</p></section>
 <section className="panel"><div className="panelheading"><h2>分时出单</h2><span>美西时间 · {start===end?start:'区间内相同小时汇总'}</span></div>{hourly.length?<ResponsiveContainer width="100%" height={250}><LineChart data={hourly}><CartesianGrid vertical={false}/><XAxis dataKey="hour"/><YAxis allowDecimals={false}/><Tooltip/><Line dataKey="orders" name="订单" stroke="#4059d7" connectNulls={false}/></LineChart></ResponsiveContainer>:<div className="empty">暂无小时明细，无法进行同一时刻对比。</div>}<p className="footnote">只展示有记录的小时；未获取的小时不填零。今日与昨日同期比较需要双方完整小时记录。</p></section>
 <div className="chartgrid">{[['model','机型销量排行'],['status','订单状态分布'],['refundReason','退款原因'],['refundStage','退款处理阶段'],['refundType','退款类型'],['creator','达人带货表现'],['video','视频成交表现']].map(([category,title])=>{const data=groupInsights(rows,category,start,end,profile);return <section className="panel" key={category}><div className="panelheading"><h2>{title}</h2><span>{data.length?`${data.length} 项`:'暂无明细'}</span></div>{data.length?<div className="insight-table"><table><thead><tr><th>项目</th><th>订单 / 笔数</th><th>{category.startsWith('refund')?'退款金额':'销售额'}</th></tr></thead><tbody>{data.map(r=><tr key={r.label}><td>{r.label}</td><td>{number(r.orders)}</td><td>{money(category.startsWith('refund')?r.refunds:r.gmv)}</td></tr>)}</tbody></table></div>:<div className="empty">尚未获取该项明细。</div>}</section>})}</div></div>;
}
export function OperationsResources(){const resources=[
 ['TikTok Creative Center','查美国手机壳高表现广告、商品趋势、关键词；拆解开头、演示与购买理由。','https://ads.tiktok.com/business/creativecenter/','官方 · 趋势与素材'],
 ['TikTok Shop Seller Center','核验履约期限、违规详情、退货处理阶段和店铺指标；以本店后台为准。','https://seller-us.tiktok.com/','官方 · 经营与规则'],
 ['Google Trends','比较图案主题与节日搜索走势，用于选题；热度不等于销量。','https://trends.google.com/trends/','选题验证'],
 ['Meta Ads Library','观察同行广告表达、产品卖点和落地页；不能据此判断成交或利润。','https://www.facebook.com/ads/library/','广告参考'],
 ['Shopify Analytics','独立站上线后分析流量来源、购物转化和商品表现，单独统计各站。','https://help.shopify.com/en/manual/reports-and-analytics/shopify-reports','独立站分析']
 ];return <div className="intelligence-stack"><div className="chartgrid">{resources.map(([title,body,url,tag])=><a className="panel resource-card" href={url} target="_blank" rel="noreferrer" key={title}><span className="eyebrow">{tag}</span><h2>{title} ↗</h2><p>{body}</p></a>)}</div><section className="panel"><h2>手机壳 POD 日常检查</h2><div className="detail-grid">{[['履约','待生产 → 打印完成 → 出库 → 首次揽收；优先核对临近平台期限的订单。'],['商品','图案、机型和壳型分别看；检查退货是否集中在同一机型或工艺。'],['达人与内容','跟踪样品签收、视频发布、商品点击和支付订单，避免只看播放量。'],['店铺异常','核对违规、取消、退款和缺失数据；异常必须能追溯到来源与统计日期。']].map(([title,body])=><div key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></section></div>}

export function AdsPanel({records}:{records:(Daily|undefined)[]}){const sum=(k:string)=>records.length&&records.every(r=>typeof r?.[k]==='number')?records.reduce((n,r)=>n+Number(r![k]),0):null;const spend=sum('ads'),impressions=sum('adImpressions'),clicks=sum('adClicks'),orders=sum('adOrders'),revenue=sum('adRevenue');const ratio=(a:number|null,b:number|null)=>a!==null&&b!==null&&b>0?a/b:null;const ctr=ratio(clicks,impressions),roas=ratio(revenue,spend);return <section className="panel"><div className="panelheading"><h2>广告投放表现</h2><span>所选区间 · 已记录广告归因口径</span></div><div className="detail-grid">{[['广告花费',money(spend)],['广告曝光',number(impressions)],['广告点击',number(clicks)],['点击率',ctr===null?'—':(ctr*100).toFixed(2)+'%'],['点击成本',money(ratio(spend,clicks))],['千次曝光成本',money(impressions!==null&&impressions>0&&spend!==null?spend/impressions*1000:null)],['广告归因订单',number(orders)],['每单广告成本',money(ratio(spend,orders))],['广告归因销售额',money(revenue)],['ROAS',roas===null?'—':roas.toFixed(2)+'×']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{spend!==null&&spend>0&&orders===0&&<div className="feedback error">本期有广告花费但归因订单为 0。先核对归因延迟、投放目标与素材表现，再决定是否调整。</div>}<p className="footnote">广告归因销售不与店铺销售相加。不同归因窗口、GMV Max 与普通广告不可混算；未记录统一口径时不作跨期判断。ROAS 不代表利润。本看台仅监测，不自动改预算。</p></section>}
