'use client';
import {aggregateRecords,datesBetween,shiftDate,type Daily,type Profile} from '@/lib/model';
const show=(v:unknown,money=false)=>typeof v==='number'?(money?'$':'')+v.toLocaleString('en-US',{maximumFractionDigits:2,minimumFractionDigits:money?2:0}):'—';
const metrics=[['gmv','销售额',true],['orders','支付订单',false],['units','件数',false],['payAmount','买家支付',true],['escrowAmount','托管金额',true],['discountAmount','优惠金额',true],['commission','达人佣金',true],['estimatedShippingFee','预估运费',true],['actualShippingCost','实际运费',true],['refunds','退款金额',true],['refundOrders','退款订单',false],['cancelled','取消订单',false],['sampleOrders','样品订单',false],['settledOrders','已结算订单',false]] as const;
export function PeriodDetails({records,profiles,start,end}:{records:Daily[];profiles:Profile[];start:string;end:string}){
 const dates=datesBetween(start,end),prior=dates.length?datesBetween(shiftDate(start,-dates.length),shiftDate(start,-1)):[];
 const total=(rs:(Daily|undefined)[],key:string)=>rs.length&&rs.every(r=>typeof r?.[key]==='number')?rs.reduce((s,r)=>s+Number(r![key]),0):null;
 const current=profiles.map(p=>aggregateRecords(records,p.id,dates)),previous=profiles.map(p=>aggregateRecords(records,p.id,prior));
 const delta=(a:number|null,b:number|null)=>a===null||b===null?'数据不足':b===0?(a===0?'持平':'上期为 0'):((a-b)/b*100).toFixed(1)+'%';
 return <div className="intelligence-stack"><section className="panel"><div className="panelheading"><h2>经营指标与上期对比</h2><span>{prior[0]||'—'} 至 {prior.at(-1)||'—'}</span></div><div className="insight-table"><table><thead><tr><th>指标</th><th>本期</th><th>上期</th><th>变化</th></tr></thead><tbody>{metrics.map(([key,label,money])=><tr key={key}><td>{label}</td><td>{show(total(current,key),money)}</td><td>{show(total(previous,key),money)}</td><td>{delta(total(current,key),total(previous,key))}</td></tr>)}</tbody></table></div><p className="footnote">预估与实际运费分别记录；未取得结算明细时不使用物流报价替代。含今天的区间尚未结束。</p></section><section className="panel"><h2>各店同期对比</h2><div className="insight-table"><table><thead><tr><th>店铺</th><th>销售额</th><th>上期销售额</th><th>变化</th><th>订单</th><th>上期订单</th><th>退款金额</th></tr></thead><tbody>{profiles.map((p,i)=><tr key={p.id}><td>{p.name}</td><td>{show(current[i]?.gmv,true)}</td><td>{show(previous[i]?.gmv,true)}</td><td>{delta(total([current[i]],'gmv'),total([previous[i]],'gmv'))}</td><td>{show(current[i]?.orders)}</td><td>{show(previous[i]?.orders)}</td><td>{show(current[i]?.refunds,true)}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>逐日经营明细</h2><div className="insight-table"><table><thead><tr><th>美西日期</th><th>销售额</th><th>订单</th><th>件数</th><th>客单价</th><th>退款金额</th><th>扣退款销售额</th><th>日报覆盖</th></tr></thead><tbody>{[...dates].reverse().map(date=>{const rs=profiles.map(p=>records.find(r=>r.profile===p.id&&r.date===date));const g=total(rs,'gmv'),o=total(rs,'orders'),f=total(rs,'refunds');return <tr key={date}><td>{date}</td><td>{show(g,true)}</td><td>{show(o)}</td><td>{show(total(rs,'units'))}</td><td>{show(g!==null&&o!==null&&o>0?g/o:null,true)}</td><td>{show(f,true)}</td><td>{show(g!==null&&f!==null?g-f:null,true)}</td><td>{rs.filter(Boolean).length}/{profiles.length} 店</td></tr>;})}</tbody></table></div></section></div>;
}
