export const initialProfiles=[
{id:'pop-1',name:'MimiMello Cases',kind:'店铺',type:'POP',environment:'紫鸟店铺 27883161858474'},
{id:'accu-1',name:'LunaMello Cases',kind:'店铺',type:'ACCU',environment:'紫鸟店铺 27886048589245'},
{id:'accu-2',name:'MelloVibe Cases',kind:'店铺',type:'ACCU',environment:'紫鸟店铺 27885954734212'},
...[1,2,3,4].map(n=>({id:`account-${n}`,name:`内容账号 0${n}`,kind:'账号',type:'TikTok',environment:''}))];
export type Profile=typeof initialProfiles[number];
export type Daily={date:string;profile:string;source:string;updatedAt?:string;[key:string]:string|number|null|undefined};
export type Report={at:string;date:string;alerts:string[]};
export type Snapshot={profile:string;checkedAt:string;source:string;activeProducts?:number|null;visitors?:number|null;productViews?:number|null;ordersToShip?:number|null;pendingReturns?:number|null;violations?:number|null;healthScore?:number|null;note?:string};
export const fields=[['gmv','销售额（USD）'],['orders','支付订单数'],['units','售出件数'],['refundOrders','退款订单数'],['cancelled','取消订单数'],['sampleOrders','样品订单数'],['refunds','退款金额（USD）'],['productCost','已售商品成本（USD）'],['shipping','运费（USD）'],['fees','平台费用（USD）'],['commission','达人佣金（USD）'],['ads','广告花费（USD）'],['otherCost','其他变动费用（USD）'],['pending','待发货订单'],['late','超时未揽收订单'],['violations','未处理违规'],['views','视频播放'],['clicks','商品点击'],['videos','发布视频数']] as const;
export const laToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const shiftDate=(date:string,days:number)=>{const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
export const yesterday=()=>shiftDate(laToday(),-1);
export const datesBetween=(start:string,end:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||start>end)return [];const result:string[]=[];for(let d=start;d<=end&&result.length<366;d=shiftDate(d,1))result.push(d);return result;};
export function contribution(r?:Daily){const keys=['gmv','refunds','productCost','shipping','fees','commission','ads','otherCost'];return r&&keys.every(k=>typeof r[k]==='number')?Math.round((Number(r.gmv)-keys.slice(1).reduce((a,k)=>a+Number(r[k]),0))*100)/100:null;}
export function aggregateRecords(records:Daily[],profile:string,dates:string[]):Daily|undefined{if(!dates.length)return undefined;const matches=dates.map(date=>records.find(r=>r.profile===profile&&r.date===date));if(matches.some(x=>!x))return undefined;const rows=matches as Daily[];const out:Daily={date:dates.at(-1)!,profile,source:rows.map(r=>r.source).filter((v,i,a)=>a.indexOf(v)===i).join('；')};for(const [key] of fields){out[key]=rows.every(r=>typeof r[key]==='number')?rows.reduce((sum,r)=>sum+Number(r[key]),0):null;}return out;}
export function inspectData(records:Daily[],profiles:Profile[],date:string){const a:string[]=[];for(const p of profiles){const r=records.find(r=>r.date===date&&r.profile===p.id);if(!r){a.push(`${p.name}：${date} 无数据，不能判断经营状态。`);continue;}const required=p.kind==='店铺'?['gmv','orders','pending','late','violations']:['views','clicks','videos'];const missing=required.filter(k=>r[k]==null);if(missing.length)a.push(`${p.name}：缺少 ${missing.map(k=>fields.find(f=>f[0]===k)?.[1]).join('、')}。`);if(p.kind==='店铺'){if(Number(r.late)>0)a.push(`${p.name}：${r.late} 单超时未揽收，优先核对工厂与物流。`);if(Number(r.violations)>0)a.push(`${p.name}：${r.violations} 项未处理违规，查看后台处理期限。`);const profit=contribution(r);if(profit===null)a.push(`${p.name}：成本或退款数据未齐，贡献利润不可计算。`);else if(profit<0)a.push(`${p.name}：当日贡献亏损 $${Math.abs(profit).toFixed(2)}，核对广告、佣金和退款。`);const prior=records.find(x=>x.profile===p.id&&x.date===shiftDate(date,-1));if(Number(prior?.orders)>=10&&typeof r.orders==='number'&&r.orders<Number(prior?.orders)*0.5)a.push(`${p.name}：订单较前一日下降超过 50%，先核对数据完整性再排查流量。`);}}return a.length?a:['已入库指标未触发当前提醒规则；不代表平台全项健康。'];}
